clean:
	rm -f *.class
	rm -f *.jar
	rm -f *.ser

run:
	javac *.java
	jar cfm pet.jar MANIFEST.MF *
	java -jar pet.jar



debug:
	javac -g Owl.java Lizard.java Panda.java Happiness.java Hunger.java Pet.java

